
server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.mariadb.jdbc.Driver             # mysql驱动包
    url: jdbc:mariadb://175.24.188.154:3360/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: ROOT#

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: tk.zlx.springcloud.entries    # 所有Entity别名类所在包
